services:
  effective_mobile:
    image: effective_mobile
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: EffectiveMobileApi/Dockerfile
    environment:
      ConnectionStrings__Postgres: "Server=host.docker.internal;Port=5432;User Id=postgres_user;Password=postgres_password;Database=postgres_db;"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"