// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241025120351_EnabledLegacyTimestamp")]
    partial class EnabledLegacyTimestamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49dd4992-3fee-4039-aef1-b85d90cf4c35"),
                            DeliveryTime = new DateTime(2024, 9, 23, 3, 56, 33, 0, DateTimeKind.Unspecified),
                            District = "Москва, Южная 25",
                            Weight = 35m
                        },
                        new
                        {
                            Id = new Guid("7cd6d7c8-d4a7-4060-9d64-d64fe283f3c7"),
                            DeliveryTime = new DateTime(2024, 12, 13, 21, 56, 13, 0, DateTimeKind.Unspecified),
                            District = "Москва, Новороссийская 20",
                            Weight = 35m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
